### ISSUE TITLE
Flash Fiction Prompt Pack 

### ISSUE THREAD

**Issue by eleanorkonik** [akaalias/obsidian-shuffle#1]
Here's my data.json

`{"variable1Name":"WORD","variable1Values":"account\nmiddle\nact\nmilk\nadjustment\nmind\nmine\nagreement\nminute\nair\nmist\namount\namusement\nmonth\nanimal\nmorning\nanswer\nmother\napparatus\nmotion\napproval\nmountain\nargument\nmove\nart\nmusic\nattack\nname\nattempt\nnation\nattention\nneed\nattraction\nnews\nauthority\nnight\nback\nnoise\nbalance\nnote\nAmaranth\t \nAmber\t \nAmethyst\t \nApricot\t \nAqua\t \nAquamarine\t \nAsparagus\t \nAuburn\t \nAzure\t \nBeige\t \nBistre\t \nBlack\t \nBlue\t \nBrass\t \nBronze\t \nBrown\t \nBuff\t \nBurgundy\t \nCamouflage \nCardinal\t \nCarmine\t \nCarrot \nCeladon\t \nCerise\t \nCerulean\t \nChampagne\t \nCharcoal\t \nChartreuse\t \nCherry\nChestnut\t \nChocolate\t \nCinnabar\t \nCinnamon\t \nCobalt\t \nCopper\t \nCoral\t \nCorn\t \nCornflower\t \nCream\t \nCrimson\t \nCyan\t \nEmerald\t \nEggplant\t \nFlax\t \nFrench Rose\t \nGold\t \nGoldenrod\t \nGreen\t \nGrey\t \nIndigo\t \nIvory\t \nJade\t \nKhaki\t \nLavender\t \nLemon\t \nLilac\t \nLime\t \nLinen\t \nMagenta\t \nMagnolia\t \nMalachite\t \nMaroon\t \nMauve\t \nMustard\t \nMyrtle\t \nNavy \nOchre\t \nOlive\t \nOrange\t \nOrchid\t \nPeach\t \nPear\t \nPeriwinkle\t \nPersimmon\t \nPine Green\t \nPink\t \nPlatinum\t \nPlum\t \nPumpkin\t \nPurple\t \nQuartz\nRaw umber\t \nRose\t \nRuby\t \nRusset\t \nRust\t\nSaffron\t \nSalmon\t \nSandy brown\t \nSangria\t \nSapphire\t \nScarlet\t \nSeashell\t \nSepia\t \nSlate\nSilver\t \nTan\t \nTangerine\t \nTaupe\t \nTeal\t \nTawny\nTerra cotta\t \nThistle\t \nTomato\t \nTurquoise\t \nUltramarine\t \nVermilion\t \nViolet\t \nViridian\t \nWheat\t \nWhite\t \nWisteria\t \nXanthic\t \nYellow\t \nZucchini\t \nbase\nnumber\nbehavior\nobservation\nbelief\noffer\nbirth\noil\nbit\noperation\nbite\nopinion\nblood\norder\nblow\norganization\nbody\nornament\nbrass\nowner\nbread\npage\nbreath\npain\nbrother\npaint\nbuilding\npaper\nburn\npart\nburst\npaste\nbusiness\npayment\nbutter\npeace\ncanvas\nperson\ncare\nplace\ncause\nplant\nchalk\nplay\nchance\npleasure\nchange\npoint\ncloth\npoison\ncoal\npolish\ncolor\nporter\ncomfort\nposition\ncommittee\npowder\ncompany\npower\ncomparison\nprice\ncompetition\nprint\ncondition\nprocess\nconnection\nproduce\ncontrol\nprofit\ncook\nproperty\ncopper\nprose\ncopy\nprotest\ncork\npull\ncopy\npunishment\ncough\npurpose\ncountry\npush\ncover\nquality\ncrack\nquestion\ncredit\nrain\ncrime\nrange\ncrush\nrate\ncry\nray\ncurrent\nreaction\ncurve\nreading\ndamage\nreason\ndanger\nrecord\ndaughter\nregret\nday\nrelation\ndeath\nreligion\ndebt\nrepresentative\ndecision\nrequest\ndegree\nrespect\ndesign\nrest\ndesire\nreward\ndestruction\nrhythm\ndetail\nrice\ndevelopment\nriver\ndigestion\nroad\ndirection\nroll\ndiscovery\nroom\ndiscussion\nrub\ndisease\nrule\ndisgust\nrun\ndistance\nsalt\ndistribution\nsand\ndivision\nscale\ndoubt\nscience\ndrink\nsea\ndriving\nseat\ndust\nsecretary\nearth\nselection\nedge\nself\neducation\nsense\neffect\nservant\nend\nerror\nshade\nevent\nshake\nexample\nshame\nexchange\nshock\nexistence\nside\nexpansion\nsign\nexperience\nsilk\nexpert\nsilver\nfact\nsister\nfall\nsize\nfamily\nsky\nfather\nsleep\nfear\nslip\nfeeling\nslope\nfiction\nsmash\nfield\nsmell\nfight\nsmile\nfire\nsmoke\nflame\nsneeze\nflight\nsnow\nflower\nsoap\nfold\nsociety\nfood\nson\nforce\nsong\nform\nsort\nfriend\nsound\nfront\nsoup\nfruit\nspace\nglass\nstage\ngold\nstart\ngovernment\nstatement\ngrain\nsteam\ngrass\nsteel\ngrip\nstep\ngroup\nstitch\ngrowth\nstone\nguide\nstop\nharbor\nstory\nharmony\nstretch\nhate\nstructure\nhearing\nsubstance\nheat\nsugar\nhelp\nsuggestion\nhistory\nsummer\nhole\nsupport\nhope\nsurprise\nhour\nswim\nhumor\nsystem\nice\ntalk\nidea\ntaste\nimpulse\ntax\nincrease\nteaching\nindustry\ntendency\nink\ntest\ninsect\ntheory\ninstrument\nthing\ninsurance\nthought\ninterest\nthunder\ninvention\ntime\niron\ntin\njelly\ntop\njoin\ntouch\njourney\ntrade\njudge\ntransport\njump\ntrick\nkick\ntrouble\nkiss\nturn\nknowledge\ntwist\nland\nunit\nlanguage\nuse\nlaugh\nvalue\nlow\nverse\nlead\nvessel\nlearning\nview\nleather\nvoice\nletter\nwalk\nlevel\nwar\nlift\nwash\nlight\nwaste\nlimit\nwater\nlinen\nwave\nliquid\nwax\nlist\nway\nlook\nweather\nloss\nweek\nlove\nweight\nmachine\nwind\nman\nwine\nmanager\nwinter\nmark\nwoman\nmarket\nwood\nmass\nwool\nmeal\nword\nmeasure\nwork\nmeat\nwound\nmeeting\nwriting\nmemory\nyear\nmetal\nworm\nangle\nknee\nant\nknife\napple\nknot\narch\nleaf\narm\nleg\narmy\nlibrary\nbaby\nline\nbag\nlip\nball\nlock\nband\nmap\nbasin\nmatch\nbasket\nmonkey\nbath\nmoon\nbed\nmouth\nbee\nmuscle\nbell\nnail\nberry\nneck\nbird\nneedle\nblade\nnerve\nboard\nnet\nboat\nnose\nbone\nnut\nbook\noffice\nboot\norange\nbottle\noven\nbox\nparcel\nboy\npen\nbrain\npencil\nbrake\npicture\nbranch\npig\nbrick\npin\nbridge\npipe\nbrush\nplane\nbucket\nplate\nbulb\nplough\nbutton\npocket\ncake\npot\ncamera\npotato\ncard\nprison\ncarriage\npump\ncart\nrail\ncat\nrat\nchain\nreceipt\ncheese\nring\nchess\nrod\nchin\nroof\nchurch\nroot\ncircle\nsail\nclock\nschool\ncloud\nscissors\ncoat\nscrew\ncollar\nseed\ncomb\nsheep\ncord\nshelf\ncow\nship\ncup\nshirt\ncurtain\nshoe\ncushion\nskin\ndog\nskirt\ndoor\nsnake\ndrain\nsock\ndrawer\nspade\ndress\nsponge\ndrop\nspoon\near\nspring\negg\nsquare\nengine\nstamp\neye\nstar\nface\nstation\nfarm\nstem\nfeather\nstick\nfinger\nstocking\nfish\nstomach\nflag\nstore\nfloor\nstreet\nfly\nsun\nfoot\ntable\nfork\ntail\nfowl\nthread\nframe\nthroat\ngarden\nthumb\ngirl\nticket\nglove\ntoe\ngoat\ntongue\ngun\ntooth\nhair\ntown\nhammer\ntrain\nhand\ntray\nhat\ntree\nhead\ntrousers\nheart\numbrella\nhook\nwall\nhorn\nwatch\nhorse\nwheel\nhospital\nwhip\nhouse\nwhistle\nisland\nwindow\njewel\nwing\nkettle\nwire\nkey","variable2Name":"LETTER","variable2Values":"a\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk\nl\nm\nn\no\np\nq\nr\ns\nt\nu\nv\nw\nx\ny\nz","variable3Name":"CHARACTER","variable3Values":"Anthropomorphic Personification\nAnti-Hero\nThe Archmage\nAudience Surrogate\nBarefoot Sage\nBlind Seer\nBlue-Collar Warlock\nBruiser with a Soft Center\nThe Chosen One\nThe Chooser of The One\nClassical Hunter\nClassic Villain\nThe Cynic\nThe Dragonslayer\nThe Drunken Sailor\nDumb Muscle\nEccentric Mentor\nEvil Overlord\nThe Fair Folk\nFalse Prophet\nThe Ferryman\nThe Fool\nFool for Love\nGentle Giant\nThe Good King\nHerald\nThe Hero\nHeroic Wannabe\nHigher Self\nHunter of Monsters\nThe Idealist\nIneffectual Loner\nThe Klutz\nKnight in Shining Armor\nLady and Knight\nLovable Rogue\nMadonna Archetype\nThe McCoy\nMentor Archetype\nMessiah Figure\nMock Millionaire\nModern Major General\nMoses Archetype\nMy Girl Back Home\nObstructive Bureaucrat\nOld Soldier\nThe Paladin\nThe Paragon\nThe Patriarch\nPerson of Mass Destruction\nPrince Charming\nRebel Leader\nRebellious Spirit\nReluctant Monster\nSeeker Archetype\nSidekick\nThe Sociopath\nStar-Crossed Lovers\nThe Storyteller\nTurn Coat\nThe Trickster\nWicked Stepmother\nWicked Witch\nWolf Man\nWorld's Best Warrior\nWorld's Most Beautiful Woman\nWorld's Strongest Man\nAbsent-Minded Professor\nThe believer\nThe skeptic\nAngry Chef\nAntagonistic Governor\nAnthropomorphic Animal\nBad Boss \nBadass Normal\nBarbarian Tribe\nThe Barber\nThe Bard \nThe Bartender \nBattle Butler\nBenevolent Precursors\nThe Berserker\nThe Big Bad Wolf\nBig Eater\nBlood Knight\nBounty Hunter\nBridezilla\nBumbling Dad \nBumbling Sidekick \nInsane Ruler \nThe Care Taker\nThe Charmer\nChatty Hairdresser\nChick Magnet\nChildhood Friend\nChivalrous Pervert\nChurch Militant\nCity Mouse\nClass Clown\nControl Freak\nCorrupt Corporate Executive \nCosmic Plaything\nCowboy Cop\nCranky Landlord\nCranky Neighbor\nCrooked Contractor\nCrossdresser\nCrouching Moron, Hidden Badass\nDad the Veteran\nDamsel Errant\nDark Messiah\nDark-Skinned Redhead\nDashing Hispanic\nDeath Seeker \nDeceptive Disciple\nDefector from Decadence\nDefrosting Ice Queen \nDeranged Taxi Driver\nDeterminator\nDetermined Widow \nDirty Coward \nThe Ditz \nBrainless Beauty \nGenius Ditz \nIdiot Savant\nUpper-Class Twit\nDumb Muscle\nDogged Nice Guy\nDoting Parent\nDouble Agent\nDream People\nDrill Sergeant Nasty\nThe Friendly Landlord\nDr. Jerk\nWorking-class hooligan\nThe Eeyore\nElegant Classical Musician\nEnigmatic Empowering Entity\nErudite Stoner\nEthnic Magician\nThe Everyman\nEvil Matriarch \nFace of a Thug\nFalse Prophet\nFarmer's Daughter\nFemme Fatale \nThe Fighting Narcissist\nThe Flapper\nForest Ranger\nGadgeteer Genius\nGirl Next Door\nGlory Hound\nGlory Seeker\nGold Digger\nBeautiful Foreigner \nGrande Dame\nGroupie\nGuile Hero\nHandsome Lech\nHalf-Human Hybrid\nHalf-Identical Twins\nHalf-Witted Hillbilly\nHardboiled Detective\nHead-Turning Beauty\nHeaven Seeker\nHell Seeker\nHeavy Sleeper\nYe Olde Hermit\nHonest John's Dealership\nHouse Husband\nHuman Weapon\nIgnorant of Their Own Ignorance\nMad Scientist's Helper\nThe Informant\nIntrepid Merchant\nKid Hero\nKindly Housekeeper\nThe Klutz\nKnight in Shining Armor\nKnow-Nothing Know-It-All\nLethal Chef\nLiteral-Minded\nLittle Jimmy\nLiving Legend\nLoony Fan\nLower-Class Lout\nMad Scientist\nMaster Swordsman\nBoastful Coward\nThe Most Wanted\nMysterious Waif\nNarcissist\nThe Nicknamer\nNon-Powered Costumed Hero\nNot with Them for the Money\nOne of the Boys\nOne-Note Cook\nOpen-Minded Parent\nOutside Man, Inside Man\nOverly Polite Pals\nPeerless Love Interest\nPerson of Mass Destruction\nPint-Sized Powerhouse\nPlucky Comic Relief\nPlucky Office Girl\nThe Nice Cheerleader\nPrince of Pranksters\nProud Warrior Race Guy\nPsycho Supporter\nThe Quarterback\nThe Reliable One\nRenaissance Man\nReplacement Goldfish\nThe Rival\nThe Roadie\nThe Rock Star\nRomantic Runner-Up\nSchool Nurse\nSelf-Made Man\nSerial Romeo\nThe Scrooge\nThe Shrink\nShrinking Violet\nSickly Neurotic Geek\nSingle-Issue Landlord\nSleazy Politician\nSmart Jerk \nNice Moron\nSmooth-Talking Talent Agent\nThe Snark Knight\nSouthern Belle\nSpirited Competitor\nStage Magician\nStarving Artist\nStarving Student\nStupid Boss\nSupreme Chef\nTall, Dark, and Handsome\nThird-Person Person\nToken Houseguest\nTomboy\nTrue Craftsman\nUnsatisfiable Customer\nUnstoppable Mailman\nWandering Minstrel\nWet Blanket Wife\nWhite Collar Worker\nWilling Channeler\nWinged Humanoid\n","shuffleNoteTemplate":"## The Prompt\n\nWrite a piece of flash fiction between 500 and 999 words that: \n\n* Includes each of the following words: $WORD, $WORD, $WORD. \n* Begins with the letter $LETTER. \n* Involves a character who matches the following archetypal trope: $CHARACTER\n\n<!-- Tips from Mary Robinette Kowal: \n\n1. In the first 2-3 sentences, establish: \n- [ ] who, using an action\n- [ ] where, with a sensory detail\n- [ ] genre, with a specific, unique detail. \n\nIn the next two sentences, set up the goal, the stakes (what are they trying to accomplish and why?) and the obstacle (what stands in their way? \n--> \n\n## The Story"}`

**Comment by akaalias** [comment]
Awesome, thank you so much! Your Flash Fiction Pack is Included in the next release (0.0.3) (I'll upload that in a minute)

**Comment by akaalias** [comment]
https://github.com/akaalias/obsidian-shuffle/releases/tag/0.0.3
